### ISSUE TITLE
Windows DC Setup Defective

### ISSUE THREAD

**Issue by bluesentinelsec** [maddev-engenuity/AdversaryEmulation#30]
The Windows DC setup script appears to be defective.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/31821088/139512021-7b2d060f-c311-4aaa-942a-d4841d17665d.png">

Steps to reproduce:

1. Download/install Windows Server 2019 (trial) in VirtualBox
2. Download AdversaryEmulation folder to desktop of Administrator user
3. execute setup-dc.ps1

**Comment by ghost** [comment]
i have the same problem, how can i resolve?
