### ISSUE TITLE
Disable MS Teams on the Windows Server

### ISSUE THREAD

**Issue by bluesentinelsec** [maddev-engenuity/AdversaryEmulation#38]
Microsoft Teams spawns immediately on login to the Windows Server 2019 system.

It is a minor nuisance to students; can we disable it in our setup scripts?

**Comment by activeshadow** [comment]
Is the Teams product needed for the training course, or can it be added to the list of products to be excluded? Per [this link](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options#id-attribute-part-of-excludeapp-element), the Teams product is a candidate for being excluded.
